name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  mobile:
    strategy:
      matrix:
        os: [macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    # Install .NET SDK
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # Adjust to your required .NET SDK version

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' # Adjust to your required .NET SDK version

    - name: Install .NET MAUI
      run: |
        dotnet workload install maui
        dotnet workload update

    - name: Install Xcode
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Display .NET Info
      run: 'dotnet --info'

    - name: Build Final Course Solution, MVVM Toolkit C#
      run: |
        dotnet build "./15. MVVM Architecture/src/2. MVVM Toolkit in C#/"        

    - name: Build Final Course Solution, MVVM Toolkit XAML
      run: |
        dotnet build "./15. MVVM Architecture/src/2a. MVVM Toolkit in XAML/"
